"""Update Call model.


Revision ID: 877dca0195f7
Revises: 1d180585ea1a
Create Date: 2024-10-12 15:44:21.211832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877dca0195f7'
down_revision = '1d180585ea1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disconnection_reason', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.drop_column('disconnection_reason')

    # ### end Alembic commands ###
